[package]
name = "wavesplatform"
version = "0.3.2"

[dependencies]
base58 = "0.2.0"
rand = "0.8.5"
tiny-bip39 = "1.0.0"

blake2 = "0.10.4"
curve25519-dalek = "2.1.3"
ed25519-dalek = "1.0.1"
sha2 = "0.10.2"
sha3 = "0.10.1"
